---
- name: 创建临时目录存放依赖包
  file:
    path: "/tmp/packages"
    state: directory
    mode: '0755'

- name: 查找所有依赖包（rpm）文件
  ansible.builtin.find:
    path: "{{ playbook_dir }}/packages/"
    patterns: '*.rpm'
    recurse: no
  delegate_to: localhost
  register: rpm_files
  run_once: true  # 仅在控制节点执行一次


- name: 复制依赖包到目标节点
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/packages/{{ item | basename }}"
    dest: "/tmp/packages/{{ item | basename }}"
    mode: '0644'
  with_items: "{{ rpm_files.files | map(attribute='path') | list }}"
  when: rpm_files.files | length > 0  # 确保只在有文件时执行


- name: 安装依赖包
  shell: "rpm -ivh /tmp/packages/{{ item | basename }} --force --nodeps"
  with_items: "{{ rpm_files.files | map(attribute='path') | list }}"
  when: rpm_files.files | length > 0  # 确保只在有文件时执行


